version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: pos-api
    image: dtuncbilek/pos-api:0.2.2


# build app
# docker compose build
# docker push dtuncbilek/pos-api:0.2.2


# docker save -o /home/dt/Documents/docker-images/seacollect-micro.tar dtuncbilek/seacollect-micro:2023.11.13

# TESTING
# scp -P 11022 /home/dt/Documents/docker-images/seacollect-micro.tar dagistan@148.251.134.103:/apps/temp/
# PROD
# scp -P 11022 /home/dt/Documents/docker-images/seacollect-micro.tar dagistan@178.63.93.62:/apps/temp/

# docker load -i /apps/temp/seacollect-micro.tar
# rm /apps/temp/seacollect-micro.tar

